### DISCUSSION TITLE
[Request] wlogout

### DISCUSSION THREAD

**Discussion by nathanjace** [eylles/pywal16#159] [Ideas]
Heyo!
Amazing job on the whole project! I am loving it so far.
I was wondering if `wlogout` could make a comeback. It used to be generated by `pywal` but it stopped, and I haven't been able to do it with `pywal16`.
I came up with a clunky script that runs whenever I generate the color scheme with pywal16:
```bash
#!/usr/bin/env bash

INPUT="${1:-$HOME/.cache/wal/colors.css}"
OUTPUT="${2:-$HOME/.cache/wal/colors-wlogout.css}"

echo "/* Generated for wlogout on $(date '+%Y-%m-%d %H:%M:%S') */" > "$OUTPUT"

grep '^ *--' "$INPUT" \
  | grep -v -- '--wallpaper' \
  | sed -E '
    s/^[[:space:]]*//;                             # remove leading whitespace
    s/--([^:]+): *([^;]+);/@define-color \1 \2;/;  # convert to @define-color
  ' >> "$OUTPUT"
```

But it would be nice if this was implemented by default!
Thanks :)

**Comment by eylles** [comment]
were ya using some template? if so do ya mind sharing it?

**Comment by nathanjace** [comment]
I didn't use a template; I simply tried and retried until wlogout started working:
I tried to import  the "raw" `colors.css` from `pywal16` on the `style.css` for `wlogout`, for example this:
```css
/* CSS variables
   Generated by 'wal' */
:root {
    --wallpaper: url("/home/user/wallpapers/cat-waves.png");

    /* Special */
    --background: #090911;
    --foreground: #c1c1c3;
    --cursor: #c1c1c3;

    /* Colors */
    --color0: #090911;
    --color1: #716B8D;
    --color2: #706D8F;
    --color3: #86749B;
    --color4: #6E8CAD;
    --color5: #7AA3C8;
    --color6: #9EA6D3;
    --color7: #c1c1c3;
    --color8: #57576b;
    --color9: #716B8D;
    --color10: #706D8F;
    --color11: #86749B;
    --color12: #6E8CAD;
    --color13: #7AA3C8;
    --color14: #9EA6D3;
    --color15: #c1c1c3;
}
```
and then running `wlogout` from terminal told me pretty much how to fix it, and so I ended up with the following `colors-wlogout.css`:
```css
/* Generated for wlogout on 2025-05-16 22:33:50 */
@define-color background #090911;
@define-color foreground #c1c1c3;
@define-color cursor #c1c1c3;
@define-color color0 #090911;
@define-color color1 #716B8D;
@define-color color2 #706D8F;
@define-color color3 #86749B;
@define-color color4 #6E8CAD;
@define-color color5 #7AA3C8;
@define-color color6 #9EA6D3;
@define-color color7 #c1c1c3;
@define-color color8 #57576b;
@define-color color9 #716B8D;
@define-color color10 #706D8F;
@define-color color11 #86749B;
@define-color color12 #6E8CAD;
@define-color color13 #7AA3C8;
@define-color color14 #9EA6D3;
@define-color color15 #c1c1c3;
```
Doing this actually applies the correct theme to `wlogout`.
<br> Sorry if I didn't understand the question...
